/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_megaease_jni_sample_BaseService */

#ifndef _Included_com_megaease_jni_sample_BaseService
#define _Included_com_megaease_jni_sample_BaseService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_megaease_jni_sample_BaseService
 * Method:    doService
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_megaease_jni_sample_BaseService_doService
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_megaease_jni_sample_BaseService
 * Method:    test_doService
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_megaease_jni_sample_BaseService_test_1doService
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
